version: '3.8'

services:
  # Database Services
  postgres:
    image: postgres:15-alpine
    container_name: finverse-postgres
    environment:
      POSTGRES_DB: finverse_db
      POSTGRES_USER: finverse_user
      POSTGRES_PASSWORD: finverse_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finverse-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finverse_user -d finverse_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: finverse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - finverse-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6
    container_name: finverse-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: finverse_user
      MONGO_INITDB_ROOT_PASSWORD: finverse_password
      MONGO_INITDB_DATABASE: finverse_documents
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - finverse-network

volumes:
  postgres_data:
  redis_data:
  mongodb_data:

networks:
  finverse-network:
    driver: bridge